# Site
name: '含水庵'
title: 'Gansui-an | 含水庵'
tagline: 'Everything about Japanese Tea Ceremony 关于日本茶道的一切知识'
SEOTitle: 'Gansui-an | 含水庵: Everything about Japanese Tea Ceremony'
description: 'Gansui-an (含水庵) is everything about Japanese Tea Ceremony. It is also known as the Way of Tea, Chanoyu, Cha-No-Yu, Chado, or Sado. Our Chado school is Urasenke. It includes knowledge of Temae, Dogu and Zen. 蔵鷺庵是关于日本茶道的博客。也被称为数寄道、茶の湯。我们的茶道流派是裏千家。这里有关于点前、茶道具、禅茶的知识。'
keyword: 'Gansui-an, 含水庵, Japanese Tea Ceremony, Way of Tea, Chanoyu, Cha-No-Yu, Chado, Sado, Temae, Urasenke, Tea Ceremony'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/gansui-an'
disqus: 'gansui-an'
email: 'mpzrlogn'
mailchimp-list: 'https://gmail.us19.list-manage.com/subscribe/post?u=9a24d35bae405fde3ea44379f&amp;id=0e5d7e628a'
google_analytics: 'UA-159401266-1'

include: ["_pages"]
permalink: /:title/

# Plugins
whitelist: [jekyll-analytics]
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-analytics

authors:
    soto:
      name:           Soto
      site:
      avatar:         /assets/images/avatar1.png
      bio:            "Hi, I am Soto 宗渡, the author of Gansui-an 含水庵, the blog you're currently viewing. I hope you like it! Ceramics, literature, and the history of Chanoyu are my interested topics."
      # email:
      # twitter:


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: soto
      avatar: /assets/images/avatar1.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      author: soto
      avatar: /assets/images/avatar1.png

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-159401266-1
    anonymizeIp: false

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
