# Site
name: '蔵鷺庵'
title: 'ZoRoAn | 蔵鷺庵'
SEOTitle: 'ZoRoAn | 蔵鷺庵: a blog about Japanese Tea Ceremony'
description: 'ZoRoAn is a blog about Japanese Tea Ceremony.'
keyword: 'ZoRoAn, 蔵鷺庵, Japanese Tea Ceremony, Way of Tea, Chanoyu, Cha-No-Yu, Chado, Sado, Temae, Urasenke, Tea Ceremony'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/ZoRoAn'
disqus: 'disqus_sHOroUPZSl'
email: 'mpzrlogn'
mailchimp-list: '0e5d7e628a'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    soshu:
      name:           Soshu
      site:
      avatar:         /assets/images/avatar1.png
      bio:            "Hi, I am Soshu 宗舟, the author of ZoRoAn 蔵鷺庵, the blog you're currently viewing. I hope you like it!"
      # email:
      # twitter:

    sochiku:
      name:           Sochiku
      site:
      avatar:         /assets/images/avatar2.png
      bio:            "Hi, I am Sochiku 宗竹, the author of ZoRoAn 蔵鷺庵, the blog you're currently viewing. I hope you like it!"
      # email:
      # twitter:

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: soshu
      avatar: /assets/images/avatar1.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      author: soshu
      avatar: /assets/images/avatar1.png

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
