# Site
name: '蔵鷺庵'
title: 'ZoRoAn | 蔵鷺庵'
SEOTitle: 'ZoRoAn | 蔵鷺庵: Everything about Japanese Tea Ceremony'
description: 'ZoRoAn (蔵鷺庵) is everything about Japanese Tea Ceremony. It is also known as the Way of Tea, Chanoyu, Cha-No-Yu, Chado, or Sado. Our Chado school is Urasenke. It includes knowledge of Temae, Dogu and Zen. 蔵鷺庵是关于日本茶道的博客。也被称为数寄道、茶の湯。我们的茶道流派是裏千家。这里有关于点前、茶道具、禅茶的知识。'
keyword: 'ZoRoAn, 蔵鷺庵, Japanese Tea Ceremony, Way of Tea, Chanoyu, Cha-No-Yu, Chado, Sado, Temae, Urasenke, Tea Ceremony'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/ZoRoAn'
disqus: 'zoroan'
email: 'mpzrlogn'
mailchimp-list: 'https://gmail.us19.list-manage.com/subscribe/post?u=9a24d35bae405fde3ea44379f&amp;id=0e5d7e628a'
google_analytics: 'UA-159401266-1'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    soshu:
      name:           Soshu
      site:
      avatar:         /assets/images/avatar1.png
      bio:            "Hi, I am Soshu 宗舟, the author of ZoRoAn 蔵鷺庵, the blog you're currently viewing. I hope you like it! Ceramics, literature, and history of Chanoyu are my interested tpics."
      # email:
      # twitter:

    sochiku:
      name:           Sochiku
      site:
      avatar:         /assets/images/avatar2.png
      bio:            "Hi, I am Sochiku 宗竹. I'm a practitioner of Japanese tea ceremony and love cooking and making Okashi (tea sweets)!"
      # email:
      # twitter:


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: soshu
      avatar: /assets/images/avatar1.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      author: soshu
      avatar: /assets/images/avatar1.png

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
